/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewRouteImport } from './routes/new'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevHeygenTestRouteImport } from './routes/dev.heygen-test'
import { Route as ProjectsProjectIdScriptRouteImport } from './routes/projects_.$projectId.script'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevHeygenTestRoute = DevHeygenTestRouteImport.update({
  id: '/dev/heygen-test',
  path: '/dev/heygen-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdScriptRoute = ProjectsProjectIdScriptRouteImport.update({
  id: '/projects_/$projectId/script',
  path: '/projects/$projectId/script',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/dev/heygen-test': typeof DevHeygenTestRoute
  '/projects/$projectId/script': typeof ProjectsProjectIdScriptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/dev/heygen-test': typeof DevHeygenTestRoute
  '/projects/$projectId/script': typeof ProjectsProjectIdScriptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/new': typeof NewRoute
  '/projects': typeof ProjectsRoute
  '/dev/heygen-test': typeof DevHeygenTestRoute
  '/projects_/$projectId/script': typeof ProjectsProjectIdScriptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/new'
    | '/projects'
    | '/dev/heygen-test'
    | '/projects/$projectId/script'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/new'
    | '/projects'
    | '/dev/heygen-test'
    | '/projects/$projectId/script'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/new'
    | '/projects'
    | '/dev/heygen-test'
    | '/projects_/$projectId/script'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NewRoute: typeof NewRoute
  ProjectsRoute: typeof ProjectsRoute
  DevHeygenTestRoute: typeof DevHeygenTestRoute
  ProjectsProjectIdScriptRoute: typeof ProjectsProjectIdScriptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/heygen-test': {
      id: '/dev/heygen-test'
      path: '/dev/heygen-test'
      fullPath: '/dev/heygen-test'
      preLoaderRoute: typeof DevHeygenTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId/script': {
      id: '/projects_/$projectId/script'
      path: '/projects/$projectId/script'
      fullPath: '/projects/$projectId/script'
      preLoaderRoute: typeof ProjectsProjectIdScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NewRoute: NewRoute,
  ProjectsRoute: ProjectsRoute,
  DevHeygenTestRoute: DevHeygenTestRoute,
  ProjectsProjectIdScriptRoute: ProjectsProjectIdScriptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
